name: ViaVersionStatus
main: com.bobcat00.viaversionstatus.ViaVersionStatus
version: ${project.version}
author: Bobcat00
api-version: 1.13
softdepend: [ViaVersion, ProtocolSupport, ViaBackwards, ViaRewind]
permissions:
  viaversionstatus.notify:
    description: Display other player client version at join
    default: op
  viaversionstatus.notify.ignoresame:
    description: Do not display version if client version equals server version
    default: false
